-- Define um parâmetro de sessão que permite a criação de um usuário
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;  

-- CRIANDO USUARIO
CREATE USER TESTE_B2W IDENTIFIED BY TESTE_B2W;

-- CONCEDENDO PERMISSÕES PARA O USUÁRIO
GRANT ALL PRIVILEGES TO TESTE_B2W;

-- CRIANDO TABELA PREDIO
CREATE TABLE PREDIO (
    CODPREDIO INT NOT NULL PRIMARY KEY,
    DESCRICAOPREDIO VARCHAR2(50)
);

-- SEQUENCIA DE PREDIO
CREATE SEQUENCE SEQ_PREDIO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- CRIANDO TABELA SALA
CREATE TABLE SALA (
    CODPREDIO INT NOT NULL,
    NUMSALA INT NOT NULL,
    DESCRICAOSALA VARCHAR2(30)NOT NULL,
    CAPACIDADE VARCHAR(4) NOT NULL,
    CONSTRAINT PK_SALA PRIMARY KEY (CODPREDIO, NUMSALA),
    CONSTRAINT FK_SALA_PREDIO FOREIGN KEY (CODPREDIO) REFERENCES PREDIO(CODPREDIO)
);

-- CRIANDO TABELA DEPARTAMENTO
CREATE TABLE DEPTO (
    CODDEPTO INT NOT NULL PRIMARY KEY,
    NOMEDEPTO VARCHAR2(30) NOT NULL
);

-- SEQUENCIA DE TITULO
CREATE SEQUENCE SEQ_DEPARTAMENTO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- TITULACAO
CREATE TABLE TITULACAO(
    CODTIT INT NOT NULL PRIMARY KEY,
    NOMETIT VARCHAR2(30)
);

-- SEQUENCIA DE TITULO
CREATE SEQUENCE SEQ_TITULO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- CRIANDO TABELA PROFESSOR
CREATE TABLE PROFESSOR (
    CODPROF INT NOT NULL PRIMARY KEY,
    CODDEPTO VARCHAR2(30) NOT NULL,
    CODTIT INT NOT NULL,
    NOMEPROF VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_PROFESSOR_TITULACAO FOREIGN KEY (CODTIT) REFERENCES TITULACAO (CODTIT)    
);

-- TABELA DE DISCIPLINA
CREATE TABLE DISCIPLINA (
    CODDEPTO INT NOT NULL,
    NUMDISC INT NOT NULL,
    NOMEDISC VARCHAR2(30),
    CREDITODISC INT,
    CONSTRAINT PK_DISC PRIMARY KEY(NUMDISC, CODDEPTO),
    CONSTRAINT FK_TURMA_DPT FOREIGN KEY(CODDEPTO) REFERENCES DEPTO (CODDEPTO)
);

-- TABELA DE PRE REQUISITO
CREATE TABLE PREREQ(
    CODDEPTO INT NOT NULL,
    NUMDISC INT NOT NULL,
    CODDEPTOPREREQ INT NOT NULL,
    NUMDISCPREREQ INT NOT NULL,
    CONSTRAINT PK_PREREQ_1 PRIMARY KEY (CODDEPTOPREREQ, NUMDISCPREREQ, CODDEPTO, NUMDISC),
    CONSTRAINT FK_PRE FOREIGN KEY (CODDEPTO, NUMDISC) REFERENCES DISCIPLINA (CODDEPTO, NUMDISC)    
);

-- TABELA DE TURMA
CREATE TABLE TURMA (
    CODDEPTO INT NOT NULL,
    NUMDISC INT NOT NULL,
    ANOSEM INT NOT NULL,
    SIGLATUR INT NOT NULL,
    CAPACIDADE INT NOT NULL,
    CONSTRAINT PK_TURMA PRIMARY KEY (SIGLATUR, ANOSEM, CODDEPTO, NUMDISC),
    CONSTRAINT FK_TURMA_DISC FOREIGN KEY (CODDEPTO, NUMDISC) REFERENCES DISCIPLINA (CODDEPTO, NUMDISC)        
);

-- CRIANDO TABELA PROFESSOR TURMA
CREATE TABLE PROFTURMA(
    CODDEPTO INT NOT NULL,
    NUMDISC INT NOT NULL,
    ANOSEM INT NOT NULL,
    SIGLATUR INT NOT NULL,
    CODPROF INT NOT NULL,
    CONSTRAINT PK_PROFTURMA PRIMARY KEY (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CODPROF),
    CONSTRAINT FK_PROFTURMA_PROF FOREIGN KEY (CODPROF) REFERENCES PROFESSOR (CODPROF),
    CONSTRAINT FK_PROFTURMA FOREIGN KEY (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR) REFERENCES TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR)    
);

-- TABELA HORARIO
CREATE TABLE HORARIO (
    CODDEPTO INT NOT NULL,
    NUMDISC INT NOT NULL,
    ANOSEM INT NOT NULL,
    SIGLATUR INT NOT NULL,
    DIASEM INT NOT NULL,
    HORAINICIO INT NOT NULL,
    CODPREDIO INT NOT NULL,
    NUMSALA INT NOT NULL,
    NUMHORAS INT NOT NULL,
    CONSTRAINT PK_HORARIO PRIMARY KEY(CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, DIASEM, HORAINICIO),
    CONSTRAINT FK_HORARIO_SALA FOREIGN KEY (CODPREDIO, NUMSALA) REFERENCES SALA (CODPREDIO, NUMSALA),    
    CONSTRAINT FK_HORARIO_TURMA FOREIGN KEY (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR) REFERENCES TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR)    
);












