--INSERCAO PREDIO
INSERT INTO PREDIO VALUES (SEQ_PREDIO.NEXTVAL, 'Vila Andrade');
INSERT INTO PREDIO VALUES (SEQ_PREDIO.NEXTVAL, 'Praça Morumbi');
INSERT INTO PREDIO VALUES (SEQ_PREDIO.NEXTVAL, 'Casa Interlagos');

--INSERCAO SALA
INSERT INTO SALA VALUES (1, 1, 'SALA 1 - PREDIO 1', 50);
INSERT INTO SALA VALUES (1, 2, 'SALA 2 - PREDIO 1', 60);
INSERT INTO SALA VALUES (1, 3, 'SALA 3 - PREDIO 1', 40);
INSERT INTO SALA VALUES (1, 4, 'SALA 4 - PREDIO 1', 35);
INSERT INTO SALA VALUES (2, 1, 'SALA 1 - PREDIO 2', 40);
INSERT INTO SALA VALUES (3, 1, 'SALA 1 - PREDIO 3', 35);

--INSERCAO TITULACAO
INSERT INTO TITULACAO (CODTIT, NOMETIT) VALUES (SEQ_TITULO.NEXTVAL, 'MESTRE'); 
INSERT INTO TITULACAO (CODTIT, NOMETIT) VALUES (SEQ_TITULO.NEXTVAL, 'DOUTOR');

--INSERCAO PROFESSOR
INSERT INTO PROFESSOR VALUES (1, 1, 1, 'DIEGO ALMEIDA');
INSERT INTO PROFESSOR VALUES (2, 1, 1, 'JULIO CESAR');
INSERT INTO PROFESSOR VALUES (3, 2, 2, 'CARLOS ALMEIDA');
INSERT INTO PROFESSOR VALUES (4, 3, 2, 'VICTOR KIDO');

--INSERCAO DEPARTAMENTO
INSERT INTO DEPTO VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'INFORMÁTICA');
INSERT INTO DEPTO VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'RH');
INSERT INTO DEPTO VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'FINANCEIRO');
INSERT INTO DEPTO VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'DOCENTE');
INSERT INTO DEPTO VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'INTERNACIONAL');

--INSERCAO DISCIPLINA
INSERT INTO DISCIPLINA VALUES (1,1, 'LÓGICA DE PROGRAMAÇÃO', 40);
INSERT INTO DISCIPLINA VALUES (1,2, 'MATEMÁTICA', 35);
INSERT INTO DISCIPLINA VALUES (3,1, 'CIÊNCIA CONTÁBIL', 25);
INSERT INTO DISCIPLINA VALUES (4,1, 'FILOSOFIA', 15);

--INSERCAO PREREQ
INSERT INTO PREREQ VALUES(1, 1, 3, 1);
INSERT INTO PREREQ VALUES(1, 2, 3, 1);
INSERT INTO PREREQ VALUES(3, 1, 1, 1);
INSERT INTO PREREQ VALUES(4, 1, 1, 1);

--INSERCAO TURMA
INSERT INTO TURMA VALUES (1, 1, 20022, 1, 40);
INSERT INTO TURMA VALUES (1, 2, 20022, 1, 40);
INSERT INTO TURMA VALUES (1, 1, 20021, 1, 40);
INSERT INTO TURMA VALUES (3, 1, 20021, 1, 40);
INSERT INTO TURMA VALUES (4, 1, 20021, 2, 40);

--INSERCAO PROFTURMA
INSERT INTO PROFTURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CODPROF) VALUES(1, 1, 20022, 1, 1);
INSERT INTO PROFTURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CODPROF) VALUES(1, 2, 20022, 1, 2);
INSERT INTO PROFTURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CODPROF) VALUES(3, 1, 20021, 1, 3);

--INSERCAO HORARIO
INSERT INTO HORARIO VALUES(1, 1, 20022, 1, 012, 1200, 1, 1, 4);
INSERT INTO HORARIO VALUES(1, 1, 20022, 1, 102, 1500, 2, 1, 4);
INSERT INTO HORARIO VALUES(1, 2, 20022, 1, 152, 1800, 1, 3, 4);
INSERT INTO HORARIO VALUES(3, 1, 20021, 1, 061, 1800, 1, 1, 3);
















