-- PERGUNTA 2
-- CRIANDO TABELA
CREATE TABLE TABELA_PRAZO
(
 CEP_INICIO NUMBER(8) NOT NULL
, CEP_FIM NUMBER(8) NOT NULL
, PRAZO NUMBER(3) NOT NULL
);

-- INSERINDO AS INFORMAÇÕES NA TABELA_PRAZO
INSERT ALL
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(1000000, 1000005, 5)
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(510101, 510104, 4)
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(510000, 510067, 4)
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(510068, 510100, 3)
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(1000006, 10000010, 5)
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(810000, 810001, 5)
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(810002, 810003, 5)
    INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES(810004, 810005, 5)
SELECT * FROM DUAL;    

-- CRIANDO TABELA PRAZO COMPACTO
CREATE TABLE TABELA_PRAZO_COMPACTADO
(
 CEP_INICIO NUMBER(8) NOT NULL
, CEP_FIM NUMBER(8) NOT NULL
, PRAZO NUMBER(3) NOT NULL
);

-- CONSULTA
SELECT CEP_INICIO, CEP_FIM, PRAZO FROM TABELA_PRAZO;

-- CRIANDO PROC
CREATE OR REPLACE NONEDITIONABLE PROCEDURE PR_PRAZO_COMPACTADO
IS  
    --VARIAVEIS DE CEP, E CONTROLES
    V_CEP_INI TABELA_PRAZO.CEP_INICIO%TYPE;
    V_CEP_FIM TABELA_PRAZO.CEP_FIM%TYPE;
    V_CEP_F TABELA_PRAZO.CEP_FIM%TYPE;
    V_PRAZO TABELA_PRAZO.PRAZO%TYPE;    
    V_CEP_AUX TABELA_PRAZO.CEP_INICIO%TYPE;
    V_INT INTEGER := 0;
    V_INT_AUX INTEGER := 0;
    V_INT_AUX_2 INTEGER := 0;

    CURSOR PRAZO_COMPAC IS        
            SELECT CEP_INICIO, CEP_FIM, CEP_FIM + 1 AS CF, PRAZO FROM TABELA_PRAZO;   

        BEGIN        
            OPEN PRAZO_COMPAC;                    
            LOOP 
                FETCH PRAZO_COMPAC INTO V_CEP_INI, V_CEP_FIM, V_CEP_F, V_PRAZO; 
                --FIM + 1 PARA O INICIO DE OUTRO         
                SELECT COUNT(*) INTO V_INT FROM TABELA_PRAZO WHERE CEP_INICIO = V_CEP_F AND PRAZO = V_PRAZO;              
                --INICIO - 1 PARA O FIM DE OUTRO                             
                SELECT COUNT(*) INTO V_INT_AUX FROM TABELA_PRAZO WHERE V_CEP_INI -1 = CEP_FIM AND PRAZO = V_PRAZO;                   
                  
                  
                IF V_INT > 0 AND V_INT_AUX <= 0 THEN
                    
                    --DETERMINAR UM NOVO CEP_FINAL
                    SELECT CEP_FIM INTO V_CEP_AUX FROM TABELA_PRAZO WHERE CEP_INICIO = V_CEP_F AND PRAZO = V_PRAZO;  

                    --REVALIDAR SE O CEP_FINAL TEM UM CEP_INICIO                                 
                    SELECT COUNT(*) INTO V_INT_AUX_2 FROM TABELA_PRAZO WHERE CEP_INICIO = V_CEP_AUX + 1 AND PRAZO = V_PRAZO;
                    
                    -- ENQUANTO FOR MAIOR QUE 0, ENTÃO VALIDAR NOVAMENTE
                    WHILE V_INT_AUX_2 > 0                    
                        LOOP
                            SELECT CEP_FIM INTO V_CEP_AUX FROM TABELA_PRAZO WHERE CEP_INICIO = V_CEP_AUX + 1 AND PRAZO = V_PRAZO;                                   
                            SELECT COUNT(*) INTO V_INT_AUX_2 FROM TABELA_PRAZO WHERE CEP_INICIO = V_CEP_AUX + 1 AND PRAZO = V_PRAZO;
                        END LOOP;                    
                    
                    --INSERÇÃO NA TABELA COMPACTADO
                    INSERT INTO TABELA_PRAZO_COMPACTADO VALUES (V_CEP_INI, V_CEP_AUX, V_PRAZO);                
                    
                ELSIF V_INT_AUX <= 0 THEN
                    --CASO SEJA REGISTRO ÚNICO SEM FIM LIGADO A OUTRO, INSERE DIRETO
                    INSERT INTO TABELA_PRAZO_COMPACTADO VALUES (V_CEP_INI, V_CEP_FIM, V_PRAZO);                
                END IF;                
                                
                EXIT WHEN PRAZO_COMPAC%NOTFOUND;
           END LOOP;                                 
           
           CLOSE PRAZO_COMPAC;                       
        END;

/

-- EXECUÇÃO DA PROC
SET SERVEROUTPUT ON

BEGIN
    PR_PRAZO_COMPACTADO;
END;

/

-- VALIDAÇÃO NA TABELA
SELECT * FROM TABELA_PRAZO_COMPACTADO;
