/*
Pergunta 1 

1 - Obter os ano-semestre em que todos os professores do departamento denominado "Informática" deram aula.
Atenção! Um simples join não é a solução.
*/
SELECT DISTINCT ANOSEM AS "ANO-SEMESTRE" FROM
    (
    SELECT PROFESSOR.CODPROF, 
           PROFESSOR.NOMEPROF, 
           PROFTURMA.ANOSEM 
    FROM PROFESSOR
    LEFT JOIN DEPTO ON PROFESSOR.CODDEPTO = DEPTO.CODDEPTO
    LEFT JOIN PROFTURMA ON PROFTURMA.CODPROF = PROFESSOR.CODPROF
    WHERE UPPER(DEPTO.NOMEDEPTO) = 'INFORMÁTICA')
;

CREATE OR REPLACE VIEW VW_ANO_SEM_INFORMATICA_AULA
AS 
SELECT DISTINCT ANOSEM AS "ANO-SEMESTRE" FROM
    (
    SELECT PROFESSOR.CODPROF, 
           PROFESSOR.NOMEPROF, 
           PROFTURMA.ANOSEM 
    FROM PROFESSOR
    LEFT JOIN DEPTO ON PROFESSOR.CODDEPTO = DEPTO.CODDEPTO
    LEFT JOIN PROFTURMA ON PROFTURMA.CODPROF = PROFESSOR.CODPROF
    WHERE UPPER(DEPTO.NOMEDEPTO) = 'INFORMÁTICA'
    WITH READ ONLY)
;

SELECT * FROM VW_ANO_SEM_INFORMATICA_AULA;

/*
2 - Obter o número de salas que foram usadas no ano-semestre 20022 por turmas do departamento denominado "Informática"
*/
SELECT COUNT(NUMSALA) AS NUM_SALAS 
FROM (SELECT HORARIO.NUMSALA
      FROM DEPTO
           RIGHT JOIN HORARIO 
           ON DEPTO.CODDEPTO = HORARIO.CODDEPTO
      WHERE UPPER(NOMEDEPTO) = 'INFORMÁTICA'
          AND HORARIO.ANOSEM = 200202
)
;

